// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data

export const fakeSessionUser = {
  id: 2,
  name: "Jesper",
  userId: "2",
};

const users = [
  {
    id: 1,
    name: "User",
    email: "user@nextmail.com",
    password: "123456",
  },
  {
    id: 2,
    name: "Jesper",
    email: "jesper.thornberg@me.com",
    password: "123456",
  },
  {
    id: 3,
    name: "Joel",
    email: "joel.thornberg@me.com",
    password: "123456",
  },
  {
    id: 4,
    name: "Sigrid",
    email: "sigrid.thornberg@me.com",
    password: "123456",
  },
  {
    id: 5,
    name: "Per",
    email: "per.thornberg@me.com",
    password: "123456",
  },
];

const offers = [
  {
    id: 1,
    from_city: "Stockholm",
    to_city: "Göteborg",
  },
  {
    id: 2,
    from_city: "Göteborg",
    to_city: "Malmö",
  },
  {
    id: 3,
    from_city: "Härnösand",
    to_city: "Umeå",
  },
];

const subscriptions = [
  {
    id: 1,
    user_id: 1,
    from_city: "GÖTEBORG",
    to_city: "STOCKHOLM",
  },
  {
    id: 2,
    user_id: 2,
    from_city: "MALMÖ",
    to_city: "STOCKHOLM",
  },
  {
    id: 3,
    user_id: 3,
    from_city: null,
    to_city: "VÄSTERVIK",
  },
  {
    id: 4,
    user_id: 2,
    from_city: "ÖSTERSUND",
    to_city: "VÄSTERVIK",
  },
  {
    id: 5,
    user_id: 1,
    from_city: "HÄRNÖSAND",
    to_city: null,
  },
  {
    id: 6,
    user_id: 5,
    from_city: "RÄTTVIK",
    to_city: "HÄRNÖSAND",
  },
];

const cities = [
  { id: 1, name: "HARSTAD" },
  { id: 2, name: "FORNEBU" },
  { id: 3, name: "STORD" },
  { id: 4, name: "LUND" },
  { id: 5, name: "LIDINGÖ" },
  { id: 6, name: "SARPSBORG" },
  { id: 7, name: "BERGEN" },
  { id: 8, name: "SKELLEFTEÅ" },
  { id: 9, name: "FOSNAVÅG" },
  { id: 10, name: "NÄSSJÖ" },
  { id: 11, name: "BRØNNØYSUND" },
  { id: 12, name: "KALMAR" },
  { id: 13, name: "RØRVIK" },
  { id: 14, name: "VÄSTERVIK" },
  { id: 15, name: "BLOMSTERDALEN" },
  { id: 16, name: "ØRSTA" },
  { id: 17, name: "ULRICEHAMN" },
  { id: 18, name: "SANDEFJORD" },
  { id: 19, name: "MOSS" },
  { id: 20, name: "HØNEFOSS" },
  { id: 21, name: "KUNGSBACKA" },
  { id: 22, name: "LJUNGBY" },
  { id: 23, name: "BILLINGSTAD" },
  { id: 24, name: "KRISTIANSUND" },
  { id: 25, name: "LYNGDAL" },
  { id: 26, name: "ODDA" },
  { id: 27, name: "BYGSTAD" },
  { id: 28, name: "ÖSTERSUND" },
  { id: 29, name: "NORRKÖPING" },
  { id: 30, name: "ESKILSTUNA" },
  { id: 31, name: "MALMÖ" },
  { id: 32, name: "ÄNGELHOLM" },
  { id: 33, name: "HAMMERFEST" },
  { id: 34, name: "LINDÅS" },
  { id: 35, name: "LARVIK" },
  { id: 36, name: "STRYN" },
  { id: 37, name: "STOCKHOLM" },
  { id: 38, name: "KARLSKOGA" },
  { id: 39, name: "NARVIK" },
  { id: 41, name: "ÖRNSKÖLDSVIK" },
  { id: 42, name: "BERG I ØSTFOLD" },
  { id: 43, name: "STAMSUND" },
  { id: 44, name: "JESSHEIM" },
  { id: 45, name: "SVOLVÆR" },
  { id: 46, name: "JÖNKÖPING" },
  { id: 47, name: "BODØ" },
  { id: 48, name: "GISLAVED" },
  { id: 49, name: "KARLSTAD" },
  { id: 50, name: "FALKÖPING" },
  { id: 51, name: "TROMSØ" },
  { id: 52, name: "FINSPÅNG" },
  { id: 53, name: "NACKA" },
  { id: 54, name: "SOGNDAL" },
  { id: 55, name: "BOLLNÄS" },
  { id: 56, name: "VÄXJÖ" },
  { id: 57, name: "HANDEN" },
  { id: 58, name: "SOLLENTUNA" },
  { id: 59, name: "BODEN" },
  { id: 60, name: "LILAND" },
  { id: 61, name: "KOKSTAD" },
  { id: 62, name: "HUNNDALEN" },
  { id: 64, name: "ÅLESUND" },
  { id: 65, name: "SUNNDALSØRA" },
  { id: 66, name: "VARA" },
  { id: 67, name: "STOKMARKNES" },
  { id: 68, name: "HESSENG" },
  { id: 69, name: "FLORØ" },
  { id: 70, name: "SOLA" },
  { id: 71, name: "SANDNESSJØEN" },
  { id: 72, name: "KATRINEHOLM" },
  { id: 73, name: "LAKSELV" },
  { id: 74, name: "ORKANGER" },
  { id: 75, name: "KARLSBORG" },
  { id: 77, name: "SKONSENG" },
  { id: 78, name: "SKÖVDE" },
  { id: 80, name: "LIDKÖPING" },
  { id: 81, name: "VÄRNAMO" },
  { id: 82, name: "STJØRDAL" },
  { id: 83, name: "HALMSTAD" },
  { id: 85, name: "HISINGSBACKA" },
  { id: 86, name: "OSLO" },
  { id: 89, name: "KRISTIANSTAD" },
  { id: 90, name: "FALUN" },
  { id: 91, name: "LULEÅ" },
  { id: 92, name: "SIMRISHAMN" },
  { id: 93, name: "LINDESNES" },
  { id: 94, name: "KUNGÄLV" },
  { id: 95, name: "ELVERUM" },
  { id: 96, name: "OTTA" },
  { id: 97, name: "LILLEHAMMER" },
  { id: 98, name: "MOLDE" },
  { id: 99, name: "BORÅS" },
  { id: 100, name: "ÅNDALSNES" },
  { id: 101, name: "FØRDE" },
  { id: 102, name: "VADSØ" },
  { id: 104, name: "ÖREBRO" },
  { id: 106, name: "MORA" },
  { id: 107, name: "SÖRBERGE" },
  { id: 110, name: "LEKNES" },
  { id: 111, name: "HUDIKSVALL" },
  { id: 113, name: "SKI" },
  { id: 114, name: "GÄVLE" },
  { id: 115, name: "EGERSUND" },
  { id: 116, name: "SKULESTADMO" },
  { id: 117, name: "KAUPANGER" },
  { id: 118, name: "KJEVIK" },
  { id: 119, name: "SANDVIKEN" },
  { id: 120, name: "MOSJØEN" },
  { id: 121, name: "ARBOGA" },
  { id: 122, name: "ASKIM" },
  { id: 123, name: "ASARUM" },
  { id: 124, name: "LUDVIKA" },
  { id: 125, name: "VIMMERBY" },
  { id: 126, name: "VIGRA" },
  { id: 127, name: "LJUSDAL" },
  { id: 128, name: "GÖTEBORG" },
  { id: 129, name: "RUD" },
  { id: 130, name: "TRONDHEIM" },
  { id: 131, name: "VISBY" },
  { id: 132, name: "ARVIDSJAUR" },
  { id: 133, name: "UPPSALA" },
  { id: 135, name: "HELSINGBORG" },
  { id: 136, name: "ENKÖPING" },
  { id: 137, name: "UMEÅ" },
  { id: 139, name: "GLOMFJORD" },
  { id: 140, name: "HÄRNÖSAND" },
  { id: 141, name: "GRIMSTAD" },
  { id: 142, name: "FINNSNES" },
  { id: 143, name: "ALINGSÅS" },
  { id: 144, name: "SKARA" },
  { id: 146, name: "GEIRANGER" },
  { id: 147, name: "KALLINGE" },
  { id: 148, name: "ANDENES" },
  { id: 149, name: "SEGELTORP" },
  { id: 150, name: "MARIESTAD" },
  { id: 154, name: "KIRUNA" },
  { id: 155, name: "SUNDSVALL" },
  { id: 156, name: "KRISTIANSAND" },
  { id: 157, name: "HAUGESUND" },
  { id: 158, name: "STEINKJER" },
  { id: 160, name: "NAMSOS" },
  { id: 161, name: "YSTAD" },
  { id: 162, name: "KONGSVINGER" },
  { id: 163, name: "VÄSTERÅS" },
  { id: 165, name: "GARDERMOEN" },
  { id: 166, name: "TØNSBERG" },
  { id: 167, name: "GRONG" },
  { id: 168, name: "UPPLANDS VÄSBY" },
  { id: 169, name: "KUNGSÄNGEN" },
  { id: 170, name: "ALTA" },
  { id: 172, name: "MJÖLBY" },
  { id: 173, name: "STAVANGER" },
  { id: 174, name: "KARLSKRONA" },
  { id: 175, name: "PORSGRUNN" },
  { id: 178, name: "ÄLMHULT" },
  { id: 180, name: "LANDVETTER" },
  { id: 181, name: "OSKARSHAMN" },
  { id: 182, name: "ARENDAL" },
  { id: 183, name: "SORTLAND" },
  { id: 184, name: "GÄLLIVARE" },
  { id: 186, name: "VETLANDA" },
  { id: 189, name: "SÖDERHAMN" },
  { id: 191, name: "NYKÖPING" },
  { id: 192, name: "SÖDERTÄLJE" },
  { id: 193, name: "VÄNERSBORG" },
  { id: 194, name: "MALMÖ/STURUP" },
  { id: 195, name: "GOL" },
  { id: 196, name: "SÄLEN" },
  { id: 197, name: "MO I RANA" },
  { id: 198, name: "AVALDSNES" },
  { id: 199, name: "LINKÖPING" },
  { id: 200, name: "HAMAR" },
  { id: 201, name: "VARBERG" },
  { id: 203, name: "BROMMA" },
  { id: 204, name: "LIERSTRANDA" },
  { id: 205, name: "HÄSSLEHOLM" },
  { id: 207, name: "STOCKHOLM (ARLANDA)" },
  { id: 208, name: "ESLÖV" },
  { id: 212, name: "MOTALA" },
  { id: 213, name: "SJÖBO" },
  { id: 214, name: "BARDUFOSS" },
  { id: 215, name: "LILLESTRØM" },
  { id: 216, name: "SOLNA" },
  { id: 217, name: "NYBRO" },
  { id: 220, name: "ÖJEBYN" },
  { id: 221, name: "LYCKSELE" },
  { id: 222, name: "UDDEVALLA" },
  { id: 223, name: "SANDNESSNJØEN" },
  { id: 225, name: "FREDRIKSTAD" },
  { id: 226, name: "BORLÄNGE" },
  { id: 227, name: "KUMLA" },
  { id: 228, name: "NORRTÄLJE" },
  { id: 229, name: "KONGSBERG" },
  { id: 230, name: "TÄBY" },
];

export { users, offers, subscriptions, cities };
